### ISSUE TITLE
Conditional Oracle Alignment

### ISSUE THREAD

**Issue by SquallSwift** [LukeGi/Card-Smith#7]
When there are only a few words in an oracle, the text alignment could be shifted to the center.

**Comment by Iuhegi** [comment]
This is not a thing on vanilla MTG cards

**Comment by SquallSwift** [comment]
Might have been thinking of some tokens I've seen then

**Comment by Iuhegi** [comment]
i can do it on tokens

**Comment by Iuhegi** [comment]
that should be an issue [add tokens]
